FaceSentiment.Dynamic.WebApp/Controllers/VideoController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FaceSentiment.Dynamic.WebApp.Models;
using System.Drawing;
using System.Drawing.Imaging;

namespace FaceSentiment.Dynamic.WebApp.Controllers
{
    public class VideoController : Controller
    {
        private List<VideoAnalyzer> Analyzers = new List<VideoAnalyzer>();
        private IDbManager db = new DbManager();
        private Connections connections;
        private List<CameraValues> cameras;
        private DetectionSetting detectionSetting;

        //FacesentimentWebService fsWS = new FacesentimentWebService();
        // GET: Video
        [Authorize]
        [HttpGet]
        public ActionResult Start(string Id)
        {
            try
            {
                
                this.CreateAnalyzers();

                Analyzers = System.Web.HttpContext.Current.Application["Analyzers"] as List<VideoAnalyzer>;
                var analyser= Analyzers.FirstOrDefault(a => a.CameraId.ToString() == Id);
                if (analyser != null)
                {
                    analyser.Start();
                    return Json(analyser.Camera, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return new HttpNotFoundResult();
                }
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(401);
            }
        }
        
        [Authorize]
        [HttpGet]
        public ActionResult Stop(string Id)
        {
            try
            {
                
                this.CreateAnalyzers();

                Analyzers = System.Web.HttpContext.Current.Application["Analyzers"] as List<VideoAnalyzer>;
                var analyser = Analyzers.FirstOrDefault(a => a.CameraId.ToString() == Id);
                if (analyser != null)
                {
                    analyser.Stop();
                    return Json(analyser.Camera, JsonRequestBehavior.AllowGet);
                }
                else
                    return new HttpNotFoundResult();
                
                /*var result = fsWS.Stop(Id);
                switch (result)
                {
                    case FacesentimentWebResult.Success:
                        return Json("Success", JsonRequestBehavior.AllowGet);

                    case FacesentimentWebResult.NotFound:
                        return new HttpNotFoundResult();

                    default:
                        return new HttpStatusCodeResult(401);
                }*/
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(401);
            }
        }
        
        [Authorize]
        [HttpGet]
        public ActionResult ViewVideo(string Id)
        {
            try
            {
                this.CreateAnalyzers();

                try
                {
                    Analyzers = System.Web.HttpContext.Current.Application["Analyzers"] as List<VideoAnalyzer>;
                    var analyser = Analyzers.FirstOrDefault(a => a.CameraId.ToString() == Id);
                    if (analyser != null && analyser.Camera.Status.Contains("Working"))
                    {
                        ViewBag.Size = analyser.ViewSize();
                        return View(analyser.Camera);
                    }
                    else
                        return RedirectToAction("WebCams","WebCamManager");
                }catch(Exception ex)
                {
                    return RedirectToAction("WebCams", "WebCamManager");
                }
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(404);
            }
        }

        [HttpGet]
        public void InitializeAnalyzer()
        {
            CreateAnalyzers();
            return;
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetFrame(string Id)
        {
            try
            {
                this.CreateAnalyzers();

                try
                {
                    Analyzers = System.Web.HttpContext.Current.Application["Analyzers"] as List<VideoAnalyzer>;
                    var analyser = Analyzers.FirstOrDefault(a => a.CameraId.ToString() == Id);
                    if (analyser != null)
                    {
                        var frame = new Bitmap(analyser.ViewFrame());
                        using (MemoryStream ms = new MemoryStream())
                        {
                            frame.Save(ms, ImageFormat.Jpeg);
                            return File(ms, "image/jpeg");
                        }
                    }
                    else
                        return new HttpNotFoundResult();
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(404);
                }
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(404);
            }
        }

        [HttpGet]
        public ActionResult GetStatus(string Id)
        {
            try
            {
                this.CreateAnalyzers();

                try
                {
                    Analyzers = System.Web.HttpContext.Current.Application["Analyzers"] as List<VideoAnalyzer>;
                    var analyser = Analyzers.FirstOrDefault(a => a.CameraId.ToString() == Id);
                    if (analyser != null)
                        return Json(analyser.Camera, JsonRequestBehavior.AllowGet);
                    else
                        return new HttpNotFoundResult();
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(401);
                }
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(404);
            }
        }

        
        private void CreateAnalyzers()
        {
            object locker;
            if (System.Web.HttpContext.Current.Application["lockCreation"] == null)
                System.Web.HttpContext.Current.Application["lockCreation"] = new object();
            locker = System.Web.HttpContext.Current.Application["lockCreation"];

            lock (locker)
            {
                if (System.Web.HttpContext.Current.Application["Analyzers"] == null)
                {
                    //Setting Strings
                    string root = System.Web.HttpContext.Current.Server.MapPath("~/Settings");
                    var ConnectionPath = string.Format("{0}\\{1}\\{2}", root,"Connections", "Connections.txt");
                    var DetectionPath = string.Format("{0}\\{1}\\{2}", root, "Connections", "DetectionSetting.txt");
                    var CameraPath = string.Format("{0}\\{1}\\{2}", root, "Connections", "CameraData.txt");


                    if (System.Web.HttpContext.Current.Application["ConnectionPath"] == null) 
                        System.Web.HttpContext.Current.Application["ConnectionPath"] = ConnectionPath;
                    
                    if(System.Web.HttpContext.Current.Application["DetectionPath"]==null)
                        System.Web.HttpContext.Current.Application["DetectionPath"] = DetectionPath;
                    if(System.Web.HttpContext.Current.Application["CameraPath"]==null)
                        System.Web.HttpContext.Current.Application["CameraPath"] = CameraPath;


                    //Setting Connection
                    connections = db.ReadConnections(ConnectionPath);
                    System.Web.HttpContext.Current.Application["Connections"] = connections;

                    //Setting DB
                    if (System.Web.HttpContext.Current.Application["DbManager"] == null) {
                        db.SetConnection(connections);
                        System.Web.HttpContext.Current.Application["DbManager"] = db;
                    }

                    //Setting detectionSettings
                    detectionSetting = db.ReadDetections(DetectionPath);
                    System.Web.HttpContext.Current.Application["Detection"] = detectionSetting;

                    //Setting cameras and Analyzer
                    cameras = db.ReadCamera(CameraPath);
                    Analyzers = new List<VideoAnalyzer>();
                    foreach (var camera in cameras)
                    {
                        Analyzers.Add(
                            new VideoAnalyzer(camera, connections, detectionSetting)
                            );
                    }
                    System.Web.HttpContext.Current.Application["Cameras"] = cameras;
                    System.Web.HttpContext.Current.Application["Analyzers"] = Analyzers;

                }
            }
        }
    }
}

FaceSentiment.Dynamic.WebApp/Views/WebCamManager/Create.cshtml
@model FaceSentiment.Dynamic.WebApp.Models.CameraValues

<hr />
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Create a new Camera</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConnectionString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConnectionString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConnectionString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MjpegStreamer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MjpegStreamer)
                    @Html.ValidationMessageFor(model => model.MjpegStreamer, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalWebcam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LocalWebcam)
                    @Html.ValidationMessageFor(model => model.LocalWebcam, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fps, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondTimeOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondTimeOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondTimeOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Cameras", "WebCams", null, new { @class = "btn btn-default" })
</div>

<script type="text/javascript">

    var ShowError = function () {
        var v=@Html.Raw(Json.Encode(ViewBag.Error));
        if (v!= null && v!="") {
            alert(v);
            v= null;
        }
    }
    ShowError();
</script>

FaceSentiment.Dynamic.WebApp/Views/WebCamManager/Delete.cshtml
@model FaceSentiment.Dynamic.WebApp.Models.CameraValues
<hr />
<hr />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Camera Value</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConnectionString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConnectionString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MjpegStreamer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MjpegStreamer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocalWebcam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocalWebcam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fps)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondTimeOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondTimeOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Delete", "DeleteOK", new { Id = Model.Id }, new { @class = "btn btn-default" })
            <!--<input type="submit" value="Delete" class="btn btn-default" />-->
        </div>
    }

    <hr />
    @Html.ActionLink("Back to Cameras", "WebCams", null, new { @class = "btn btn-default" })
</div>

<script type="text/javascript">
    
    var ShowError = function () {
        var v=@Html.Raw(Json.Encode(ViewBag.Error));
        if (v!= null && v!="") {
            alert(v);
            v= null;
        }
    }
    ShowError();
</script>

FaceSentiment.Dynamic.WebApp/Views/WebCamManager/Details.cshtml
@model FaceSentiment.Dynamic.WebApp.Models.CameraValues

<hr />
<hr />
<div>
    <h4>Details of Camera</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConnectionString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConnectionString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MjpegStreamer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MjpegStreamer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocalWebcam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocalWebcam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fps)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondTimeOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondTimeOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })
</p>
<p>
    @Html.ActionLink("Back to Cameras", "WebCams", null, new { @class = "btn btn-default" })
</p>

FaceSentiment.Dynamic.WebApp/Views/WebCamManager/Edit.cshtml
@model FaceSentiment.Dynamic.WebApp.Models.CameraValues

<hr />
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Camera</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConnectionString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConnectionString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConnectionString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MjpegStreamer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MjpegStreamer)
                    @Html.ValidationMessageFor(model => model.MjpegStreamer, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalWebcam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LocalWebcam)
                    @Html.ValidationMessageFor(model => model.LocalWebcam, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fps, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondTimeOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondTimeOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondTimeOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Cameras", "WebCams")
</div>
<script type="text/javascript">

    var ShowError = function () {
        var v=@Html.Raw(Json.Encode(ViewBag.Error));
        if (v!= null && v!="") {
            alert(v);
            v= null;
        }
    }
    ShowError();
</script>

FaceSentiment.Dynamic.WebApp/Views/WebCamManager/WebCamsAuthorize.cshtml
@model IEnumerable<FaceSentiment.Dynamic.WebApp.Models.CameraValues>

<hr />
<hr />
<h4>WebCam Manager</h4>
<hr />
<p>
    <a href="@Url.Action("Create")" style="color:black">
        <img src="/Media/NewCameraImage" onmouseover="NewCameraMouseOver(this)" onmouseout="NewCameraMouseOut(this)" width="30" height="30" />New Camera
    </a>
</p>
<table class="table">
    <tr>
        <th>
            Start
        </th>
        <th>
            Stop
        </th>
        <th>
            @Html.DisplayName("Type");
        </th>
        <th>
            @Html.DisplayName("Position");
        </th>
        <th>
            @Html.DisplayName("Location");
        </th>
        <th>
            @Html.DisplayName("Status");
        </th>
        <th>
            @Html.DisplayName("Face / Request");
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img alt="Start" src="/Media/StartButtonImage" onmouseover="StartMouseOver(this)" onmouseout="StartMouseOut(this)" onclick='StartVideo(this)' data-assigned-id="@item.Id.ToString()" width="38" height="38" />
            </td>
            <td>
                <img alt="Stop" src="/Media/StopButtonImage" onmouseover="StopMouseOver(this)" onmouseout="StopMouseOut(this)" onclick='StopVideo(this)' data-assigned-id="@item.Id.ToString()" width="35" height="35" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td id="Status @item.Id.ToString()">
                Stopped
            </td>
            <td id="Face @item.Id.ToString()">
                0 / 0
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id.ToString() },new { @style = "color:black" }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id.ToString() }, new { @style = "color:black" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id.ToString() }, new { @style = "color:black" })|
                <!--@Html.ActionLink("View", "ViewVideo","Video", new { id = item.Id.ToString() }, new { @style = "color:black", @class="btn btn-default" })-->
                <!--<input type="button" value="View" onclick='ViewVideo(this)' data-assigned-id="@item.Id.ToString()" />-->
            </td>
        </tr>

    }
</table>


<script type="text/javascript">
    var listIdWorking = [];
    var populate = function () {
        var m = @Html.Raw(Json.Encode(Model));
        for (var i = 0; i < m.length;i++)
        {
            listIdWorking.push(m[i].Id);
        }

    };
    var StartVideo = function (elem) {
        var Id = $(elem).data('assigned-id');
        $.ajax({
            type: 'GET',
            url: '/Video/Start/' + Id,
            dataType: 'json',
            success: function (data) {
                alert("Started Stream for Camera:\n"+ data.Type + ": " + data.Location + " " + data.Position );
                //listIdWorking.push(data.Id);
            },
            error: function (data) {
                alert("Error while starting the camera");
            }
        })
    };
    var StopVideo = function (elem) {
        var Id = $(elem).data('assigned-id');
        $.ajax({
            type: 'GET',
            url: '/Video/Stop/' + Id,
            dataType: 'json',
            success: function (data) {
                alert("Stopped Stream for Camera:\n" + data.Type +": " +data.Location +" "+data.Position );
                var index = listIdWorking.indexOf(data.Id);
                var cameraStatusId = "Status " + data.Id;
                document.getElementById(cameraStatusId).innerHTML = "Stopped";
            },
            error: function (data) {
                alert("Error while stopping the camera");
            }
        })
    };
    var ViewVideo = function (elem) {
        var Id = $(elem).data('assigned-id');
        $.ajax({
            type: 'GET',
            url: '/Video/ViewVideo/' + Id,
            dataType: 'json',
            success: function (data) {
                alert("Camera " + data.Id + " : \nStatus :" + data.Status);
            },
            error: function (data) {
                alert("Error");
            }
        })
    };

    var StartMouseOver = function (elem) {
        $(elem).attr("src", "/Media/StartButtonOnmouseImage");
    };
    var StartMouseOut = function (elem) {
        $(elem).attr("src", "/Media/StartButtonImage");
    };
    var StopMouseOver = function (elem) {
        $(elem).attr("src", "/Media/StopButtonOnmouseImage");
    };
    var StopMouseOut = function (elem) {
        $(elem).attr("src", "/Media/StopButtonImage");
    };
    var NewCameraMouseOver = function (elem) {
        $(elem).attr("src", "/Media/NewCameraOnMouseImage");
    };
    var NewCameraMouseOut = function (elem) {
        $(elem).attr("src", "/Media/NewCameraImage");
    };
    var ascStatus= function(){
        if (listIdWorking.length != 0 ) {
            listIdWorking.forEach(function(camId){

                var cameraStatusId = "Status " + camId;
                var cameraFacedetectId = "Face " + camId;
                $.ajax({
                    type: 'GET',
                    url: '/Video/GetStatus/' + camId,
                    dataType: 'json',
                    success: function (data) {
                        document.getElementById(cameraStatusId).innerHTML = data.Status;
                        document.getElementById(cameraFacedetectId).innerHTML = data.FaceDetectedOnRequest[0] + " / " + data.FaceDetectedOnRequest[1];
                    },
                    error: function (data) {
                        document.getElementById(cameraStatusId).innerHTML = "Status Error";
                    }
                });

            });
        }

        setTimeout(ascStatus, 5000);
    };
    var ShowError = function () {
        var v=@Html.Raw(Json.Encode(ViewBag.Error));
        if (v!= null && v!="") {
            alert(v);
            v= null;
        }
    }
    populate();
    ascStatus();
    ShowError()

</script>